services:
  - type: web
    name: service-registry
    env: docker
    plan: free
    repo: https://github.com/your-username/employee-management-microservices
    branch: main
    rootDir: service-registry
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: department-service
    env: docker
    plan: free
    repo: https://github.com/your-username/employee-management-microservices
    branch: main
    rootDir: department-service/department-service
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://departments_jgoc_user:q8CsveKX4dIbZjC06pSvLF8sh2AXjvVN@dpg-d11r6949c44c73fkvg1g-a.oregon-postgres.render.com/departments_jgoc
      - key: SPRING_DATASOURCE_USERNAME
        value: departments_jgoc_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: q8CsveKX4dIbZjC06pSvLF8sh2AXjvVN
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://employee-management-microservices.onrender.com

  - type: web
    name: api-gateway
    env: docker
    plan: free
    repo: https://github.com/your-username/employee-management-microservices
    branch: main
    rootDir: api-gateway
    envVars:
      - key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        value: https://service-registry.onrender.com/eureka

  - type: web
    name: vaadin-demo
    env: docker
    plan: free
    repo: https://github.com/your-username/employee-management-microservices
    branch: main
    rootDir: vaadin-demo
